const icons = {
  adventure: '🧭',
  apple: '🍎',
  artist: '🎨',
  backpack: '🎒',
  baseball: '⚾',
  basket: '🧺',
  bicycle: '🚲',
  birthday: '🎂',
  blanket: '🛏️',
  bracelet: '💎',
  breakfast: '🍳',
  bridge: '🌉',
  brush: '🖌️',
  building: '🏢',
  calendar: '📅',
  camera: '📷',
  campfire: '🔥',
  carpenter: '🪚',
  castle: '🏰',
  chair: '🪑',
  champion: '🏆',
  chocolate: '🍫',
  classroom: '🏫',
  cloud: '☁️',
  computer: '💻',
  cookie: '🍪',
  cupboard: '🗄️',
  daughter: '👧',
  dinosaur: '🦖',
  discover: '🔎',
  doctor: '🩺',
  dragon: '🐉',
  elephant: '🐘',
  envelope: '✉️',
  farmer: '🚜',
  favorite: '⭐',
  firework: '🎆',
  flower: '🌸',
  football: '🏈',
  forest: '🌲',
  friendly: '🤝',
  garden: '🌱',
  glasses: '👓',
  grandma: '👵',
  grandpa: '👴',
  guitar: '🎸',
  hamburger: '🍔',
  homework: '📓',
  hospital: '🏥',
  house: '🏠',
  jungle: '🌴',
  keyboard: '⌨️',
  language: '💬',
  library: '📚',
  magnet: '🧲',
  market: '🛒',
  monkey: '🐒',
  mountain: '⛰️',
  necklace: '📿',
  notebook: '📒',
  number: '🔢',
  orange: '🍊',
  painting: '🖼️',
  pencil: '✏️',
  pickle: '🥒',
  pillow: '🛌',
  pirate: '🏴‍☠️',
  planet: '🪐',
  puzzle: '🧩',
  question: '❓',
  rabbit: '🐇',
  rainbow: '🌈',
  rocket: '🚀',
  sandwich: '🥪',
  school: '🏫',
  scissors: '✂️',
  shadow: '👤',
  shoulder: '💪',
  silver: '🥈',
  soccer: '⚽',
  squirrel: '🐿️',
  starfish: '⭐',
  stream: '🏞️',
  summer: '☀️',
  thunder: '⛈️',
  ticket: '🎟️',
  tiger: '🐯',
  train: '🚆',
  treasure: '💰',
  triangle: '🔺',
  tunnel: '🚇',
  vacuum: '🧹',
  wallet: '👛',
  water: '💧',
  window: '🪟',
  winter: '❄️',
  yellow: '💛',
  zipper: '🤐'
};

function makeImage(word, clue) {
  const icon = icons[word] ?? '✨';
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 506">
      <defs>
        <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
          <stop offset="0%" stop-color="#fff4c7"/>
          <stop offset="52%" stop-color="#d9f4ee"/>
          <stop offset="100%" stop-color="#dfe9ff"/>
        </linearGradient>
      </defs>
      <rect width="900" height="506" fill="url(#bg)"/>
      <circle cx="170" cy="118" r="82" fill="#ffffff" opacity="0.55"/>
      <circle cx="744" cy="388" r="112" fill="#ffffff" opacity="0.45"/>
      <text x="450" y="238" text-anchor="middle" font-size="156">${icon}</text>
      <text x="450" y="354" text-anchor="middle" font-family="Arial, sans-serif" font-size="34" font-weight="800" fill="#345268">${clue}</text>
    </svg>
  `;

  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

function buildWord(word, clue, customImage) {
  const hasCustomImage = typeof customImage === 'string' && /^(https?:|data:image)/.test(customImage);

  return {
    word,
    clue,
    imageAlt: `${word} picture`,
    image: hasCustomImage ? customImage : makeImage(word, clue)
  };
}

export const wordLevels = {
  basic: [
    buildWord('apple', 'A crunchy red or green fruit', 'apple fruit'),
    buildWord('tiger', 'A big striped cat', 'tiger animal'),
    buildWord('chair', 'You sit on it', 'wooden chair'),
    buildWord('train', 'It rides on tracks', 'train railway'),
    buildWord('cloud', 'It floats in the sky', 'white cloud sky'),
    buildWord('brush', 'You use it to paint or clean', 'paint brush'),
    buildWord('house', 'A place where people live', 'small house'),
    buildWord('water', 'You drink it when you are thirsty', 'glass of water'),
    buildWord('flower', 'A colorful plant that can smell sweet', 'flower garden'),
    buildWord('school', 'A place where children learn', 'school classroom')
  ],
  intermediate: [
    buildWord('bicycle', 'It has two wheels and pedals', 'child bicycle'),
    buildWord('rainbow', 'Colors after rain', 'rainbow sky'),
    buildWord('blanket', 'It keeps you warm in bed', 'cozy blanket'),
    buildWord('library', 'A place with many books', 'library books'),
    buildWord('pencil', 'You write and draw with it', 'yellow pencil'),
    buildWord('market', 'A place to buy food', 'fruit market'),
    buildWord('window', 'You look through it', 'sunny window'),
    buildWord('garden', 'A place where plants grow', 'vegetable garden'),
    buildWord('rocket', 'It flies into space', 'rocket launch'),
    buildWord('camera', 'It takes pictures', 'camera photography'),
    buildWord('planet', 'Earth is one of these', 'planet space'),
    buildWord('pirate', 'A sailor in adventure stories', 'pirate ship'),
    buildWord('castle', 'A large old home for kings or queens', 'castle'),
    buildWord('forest', 'A place with many trees', 'forest trees'),
    buildWord('monkey', 'An animal that can climb and swing', 'monkey animal'),
    buildWord('rabbit', 'A small animal with long ears', 'rabbit animal'),
    buildWord('puzzle', 'A game with pieces to fit together', 'jigsaw puzzle'),
    buildWord('guitar', 'A music instrument with strings', 'guitar instrument'),
    buildWord('soccer', 'A sport played by kicking a ball', 'soccer ball'),
    buildWord('ticket', 'You use it to enter a place or ride', 'ticket'),
    buildWord('cookie', 'A small sweet snack', 'cookie dessert'),
    buildWord('pillow', 'You rest your head on it', 'bed pillow'),
    buildWord('basket', 'A container for carrying things', 'basket'),
    buildWord('dragon', 'A pretend creature in many stories', 'friendly dragon illustration'),
    buildWord('doctor', 'A person who helps sick people', 'doctor stethoscope'),
    buildWord('farmer', 'A person who grows food', 'farmer field'),
    buildWord('magnet', 'It pulls some metals toward it', 'magnet science'),
    buildWord('tunnel', 'A path that goes under something', 'tunnel'),
    buildWord('silver', 'A shiny gray color or metal', 'silver metal'),
    buildWord('summer', 'The warm season after spring', 'summer beach'),
    buildWord('winter', 'The cold season with snow in some places', 'winter snow'),
    buildWord('jungle', 'A warm forest with many plants', 'jungle plants'),
    buildWord('number', 'A symbol used for counting', 'numbers classroom'),
    buildWord('orange', 'A fruit and also a color', 'orange fruit'),
    buildWord('pickle', 'A small green food with a sour taste', 'pickle food'),
    buildWord('shadow', 'A dark shape made when light is blocked', 'shadow light'),
    buildWord('stream', 'A small flowing river', 'stream water'),
    buildWord('thunder', 'The loud sound after lightning', 'thunderstorm sky'),
    buildWord('vacuum', 'A machine that cleans floors', 'vacuum cleaner'),
    buildWord('wallet', 'A small case for money or cards', 'wallet'),
    buildWord('yellow', 'The color of lemons and sunshine', 'yellow color'),
    buildWord('zipper', 'It opens and closes a jacket or bag', 'zipper closeup'),
    buildWord('artist', 'A person who makes art', 'artist painting'),
    buildWord('bridge', 'It helps people cross over water or roads', 'bridge')
  ],
  hard: [
    buildWord('adventure', 'An exciting trip or story', 'child adventure forest'),
    buildWord('dinosaur', 'An animal from long ago', 'dinosaur skeleton'),
    buildWord('treasure', 'Something valuable to find', 'treasure chest'),
    buildWord('hospital', 'A place where doctors help people', 'hospital building'),
    buildWord('triangle', 'A shape with three sides', 'triangle shape'),
    buildWord('calendar', 'It shows days and months', 'calendar desk'),
    buildWord('backpack', 'A bag you carry on your back', 'school backpack'),
    buildWord('baseball', 'A sport played with a bat and ball', 'baseball glove'),
    buildWord('birthday', 'The day someone was born', 'birthday cake'),
    buildWord('bracelet', 'Jewelry worn around the wrist', 'bracelet'),
    buildWord('breakfast', 'The first meal of the day', 'breakfast plate'),
    buildWord('building', 'A large structure with walls and rooms', 'building architecture'),
    buildWord('campfire', 'A small outdoor fire for warmth or cooking', 'campfire'),
    buildWord('carpenter', 'A person who builds things with wood', 'carpenter tools'),
    buildWord('champion', 'A winner in a contest or sport', 'champion trophy'),
    buildWord('chocolate', 'A sweet brown food', 'chocolate bar'),
    buildWord('classroom', 'A room where students learn', 'classroom'),
    buildWord('computer', 'A machine used for games, writing, and learning', 'computer laptop'),
    buildWord('cupboard', 'A cabinet for storing dishes or food', 'kitchen cupboard'),
    buildWord('daughter', 'A girl child in a family', 'family child'),
    buildWord('discover', 'To find or learn something new', 'discover science'),
    buildWord('elephant', 'A very large animal with a trunk', 'elephant animal'),
    buildWord('envelope', 'A paper cover for a letter', 'envelope mail'),
    buildWord('favorite', 'The one you like best', 'favorite star'),
    buildWord('firework', 'A bright burst of light in the sky', 'fireworks'),
    buildWord('football', 'A sport played with an oval ball', 'american football'),
    buildWord('friendly', 'Kind and nice to others', 'friendly children'),
    buildWord('glasses', 'They help some people see better', 'eyeglasses'),
    buildWord('grandma', 'Your parent\'s mother', 'grandmother family'),
    buildWord('grandpa', 'Your parent\'s father', 'grandfather family'),
    buildWord('hamburger', 'A sandwich with a round bun', 'hamburger food'),
    buildWord('homework', 'School work done at home', 'homework notebook'),
    buildWord('keyboard', 'It has keys for typing', 'computer keyboard'),
    buildWord('language', 'Words people use to talk or write', 'language learning'),
    buildWord('mountain', 'A very tall natural landform', 'mountain landscape'),
    buildWord('necklace', 'Jewelry worn around the neck', 'necklace'),
    buildWord('notebook', 'A book of blank pages for writing', 'notebook pencil'),
    buildWord('painting', 'A picture made with paint', 'painting art'),
    buildWord('question', 'Something you ask when you want to know', 'question mark'),
    buildWord('sandwich', 'Food made with filling between bread', 'sandwich food'),
    buildWord('scissors', 'A tool used to cut paper', 'scissors tool'),
    buildWord('shoulder', 'The body part between your neck and arm', 'shoulder body'),
    buildWord('squirrel', 'A small animal with a bushy tail', 'squirrel animal'),
    buildWord('starfish', 'A sea animal shaped like a star', 'starfish beach')
  ]
};
